https://github.com/josevalladares99/datawarehouse-seguros.git

In [35]:
import pandas as pd
import re

In [36]:
url = "https://raw.githubusercontent.com/josevalladares99/datawarehouse-seguros/main/data/clientes.csv"

In [37]:
df = pd.read_csv(url)
print("Dataset cargado correctamente")

Dataset cargado correctamente

In [38]:
display(df.head())

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

BLOQUE 2: Exploración del DATASET

In [39]:
print("Primeras filas del DATASET")
display(df.head())

Primeras filas del DATASET

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [40]:
print("Dimensiones del dataset (filas, columnas)")
print(df.shape)

Dimensiones del dataset (filas, columnas)
(3030, 7)

In [41]:
print("Columnas del dataset")
print(df.columns)

Columnas del dataset
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento'],
      dtype='object')

In [42]:
print("Tipo de datos")
print(df.dtypes)

Tipo de datos
id_cliente           int64
nombre              object
email               object
genero              object
fecha_nacimiento    object
ciudad              object
segmento            object
dtype: object

In [43]:
print("Valores nulos por columnas")
print(df.isnull().sum())

Valores nulos por columnas
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [44]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

BLOQUE 3: LIMPIEZA DE DATOS

In [45]:
# 1) Trim en columnas de texto (quita espacios al inicio/fin)
for col in df.columns:
    if pd.api.types.is_object_dtype(df[col]):
        df[col] = df[col].astype(str).str.strip()

# 2) Normalización de GÉNERO -> {Hombre, Mujer}
GENERO_MAP = {
    # masculino
    "hombre":"Hombre","masculino":"Hombre","masc":"Hombre","m":"Hombre","male":"Hombre",
    # femenino
    "mujer":"Mujer","femenino":"Mujer","fem":"Mujer","f":"Mujer","female":"Mujer"
}
def normaliza_genero(x):
    if pd.isna(x):
        return pd.NA
    k = str(x).strip().lower()
    return GENERO_MAP.get(k, pd.NA)

if 'genero' in df.columns:
    df['genero'] = df['genero'].apply(normaliza_genero)

# 3) Normalización de CIUDAD (canónica)
#    Canónicos: San Salvador, Santa Ana, San Miguel, La Libertad, Sonsonate
def normaliza_ciudad(x):
    if pd.isna(x):
        return pd.NA
    k = re.sub(r"[.\s]+", " ", str(x).strip().lower())
    k = (k.replace("sanmiguel","san miguel")
           .replace("s miguel","san miguel")
           .replace("sansalvador","san salvador")
           .replace("s salvador","san salvador")
           .replace("ss","san salvador")
           .replace("santaana","santa ana")
           .replace("sta ana","santa ana")
           .replace("lalibertad","la libertad")
           .replace("l libertad","la libertad")
           .replace("sonso","sonsonate"))
    can = k.title()
    ALLOWED = {"San Salvador","Santa Ana","San Miguel","La Libertad","Sonsonate"}
    return can if can in ALLOWED else pd.NA

if 'ciudad' in df.columns:
    df['ciudad'] = df['ciudad'].apply(normaliza_ciudad)

# 4) Normalización de SEGMENTO -> {Regular, Premium, VIP, Pyme}
SEG_MAP = {"regular":"Regular","premium":"Premium","vip":"VIP","pyme":"Pyme"}
def normaliza_segmento(x):
    if pd.isna(x):
        return pd.NA
    k = str(x).strip().lower()
    return SEG_MAP.get(k, pd.NA)

if 'segmento' in df.columns:
    df['segmento'] = df['segmento'].apply(normaliza_segmento)

# 5) Estandarizar FECHA_NACIMIENTO -> 'fecha_nacimiento_dt' (solo parseo; no reglas de edad)
def parse_fecha(series: pd.Series) -> pd.Series:
    s = series.astype(str).str.strip()
    return pd.to_datetime(s, errors="coerce", dayfirst=True, infer_datetime_format=True)

if 'fecha_nacimiento' in df.columns:
    df['fecha_nacimiento_dt'] = parse_fecha(df['fecha_nacimiento'])

# 6) Eliminar duplicados exactos de fila
df = df.drop_duplicates()

/tmp/ipykernel_290/191710404.py:59: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  return pd.to_datetime(s, errors="coerce", dayfirst=True, infer_datetime_format=True)
/tmp/ipykernel_290/191710404.py:59: UserWarning: Parsing dates in %Y/%m/%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(s, errors="coerce", dayfirst=True, infer_datetime_format=True)

Separación de datos validos y rechazados

In [46]:
EMAIL_REGEX = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"
CIUDAD_VALIDAS = {"San Salvador","Santa Ana","San Miguel","La Libertad","Sonsonate"}
SEG_VALIDOS    = {"Regular","Premium","VIP","Pyme"}

def es_cliente_valido(row):
    # id_cliente
    if pd.isna(row['id_cliente']):
        return False

    # nombre (mínimo 3 caracteres útiles)
    if pd.isna(row['nombre']) or len(str(row['nombre']).strip()) < 3:
        return False

    # email (formato)
    if pd.isna(row['email']) or re.match(EMAIL_REGEX, str(row['email']).strip()) is None:
        return False

    # genero (normalizado)
    if pd.isna(row['genero']) or row['genero'] not in {"Hombre","Mujer"}:
        return False

    # fecha_nacimiento parseada
    if pd.isna(row.get('fecha_nacimiento_dt', pd.NaT)):
        return False

    # ciudad (catálogo canónico)
    if pd.isna(row['ciudad']) or row['ciudad'] not in CIUDAD_VALIDAS:
        return False

    # segmento (catálogo canónico)
    if pd.isna(row['segmento']) or row['segmento'] not in SEG_VALIDOS:
        return False

    return True

# Separación (idéntico patrón a lo que vienes haciendo)
valid_mask = df.apply(es_cliente_valido, axis=1)
clientes_validos    = df[valid_mask].copy()
clientes_rechazados = df[~valid_mask].copy()

Motivo rechazo

In [47]:
def motivo_rechazo_cliente(row):
    motivos = []

    # id_cliente
    if pd.isna(row.get('id_cliente')):
        motivos.append("id_cliente_nulo")

    # nombre
    if pd.isna(row.get('nombre')) or len(str(row.get('nombre')).strip()) < 3:
        motivos.append("nombre_invalido")

    # email
    email = row.get('email')
    if pd.isna(email) or re.match(EMAIL_REGEX, str(email).strip()) is None:
        motivos.append("email_invalido")

    # genero
    genero = row.get('genero')
    if pd.isna(genero) or genero not in {"Hombre","Mujer"}:
        motivos.append("genero_invalido")

    # fecha parseada
    if pd.isna(row.get('fecha_nacimiento_dt', pd.NaT)):
        motivos.append("fecha_nacimiento_invalida")

    # ciudad
    ciudad = row.get('ciudad')
    if pd.isna(ciudad):
        motivos.append("ciudad_nula")
    elif ciudad not in CIUDAD_VALIDAS:
        motivos.append("ciudad_fuera_catalogo")

    # segmento
    segmento = row.get('segmento')
    if pd.isna(segmento):
        motivos.append("segmento_nulo")
    elif segmento not in SEG_VALIDOS:
        motivos.append("segmento_invalido")

    return ", ".join(motivos)

# Aplicar a los rechazados
if not clientes_rechazados.empty:
    clientes_rechazados["motivo_rechazo"] = clientes_rechazados.apply(motivo_rechazo_cliente, axis=1)

In [48]:

# Dejar 'fecha_nacimiento' estandarizada (datetime) en curated
if 'fecha_nacimiento' in clientes_validos.columns:
    clientes_validos = clientes_validos.drop(columns=['fecha_nacimiento'])
clientes_validos = clientes_validos.rename(columns={'fecha_nacimiento_dt':'fecha_nacimiento'})

Exportar archivos

In [51]:

clientes_validos.to_csv('clientes_curated_ejercicio.csv', index=False)
clientes_rechazados.to_csv('clientes_rejects_ejercicio.csv', index=False)

In [52]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:oBPWTDnwlDkov4SzFc8zpJwu1kTOiolN@dpg-d6qu7s450q8c73bpf590-a.oregon-postgres.render.com/etl_seguros_k3sp"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [53]:

clientes_validos.to_sql(
    "clientes_curated_ejercicio",
    con=engine,
    if_exists="replace",
    index=False
)

clientes_rechazados.to_sql(
    "clientes_rejects_ejercicio",
    con=engine,
    if_exists="replace",
    index=False
)

720

In [54]:
pd.read_sql(
"SELECT * FROM clientes_curated_ejercicio LIMIT 10",
engine
)

,id_cliente,nombre,email,genero,ciudad,segmento,fecha_nacimiento
0,13,Carlos Santos Morales,carlos.santos.morales6@correo.com,Hombre,Santa Ana,Regular,1975-08-02
1,17,Diego García Flores,diego.garcia.flores3@seguro.sv,Mujer,La Libertad,VIP,1980-06-10
2,28,Paula Castillo Santos,paula.castillo.santos0@gmail.com,Mujer,San Salvador,Premium,1978-06-21
3,33,Ricardo Chávez García,ricardo.chavez.garcia5@seguro.sv,Mujer,San Miguel,VIP,1993-08-26
4,46,Daniela Santos Reyes,daniela.santos.reyes4@seguro.sv,Hombre,La Libertad,Premium,1949-01-01
5,47,Andrés Pérez García,andres.perez.garcia5@example.com,Mujer,La Libertad,Regular,1982-02-13
6,50,Marta Martínez Castillo,marta.martinez.castillo1@correo.com,Hombre,La Libertad,Premium,1972-02-28
7,55,Ana Santos Martínez,ana.santos.martinez6@example.com,Hombre,San Miguel,Premium,1994-05-27
8,67,Marta Pérez Torres,marta.perez.torres4@correo.com,Mujer,San Miguel,VIP,1940-04-02
9,70,José Chávez Mendoza,jose.chavez.mendoza0@mail.com,Hombre,San Miguel,VIP,1959-11-16

In [55]:
pd.read_sql(
"SELECT * FROM clientes_rejects_ejercicio LIMIT 10",
engine
)

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento,fecha_nacimiento_dt,motivo_rechazo
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,San Miguel,None,2011-11-24,segmento_nulo
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,None,01-02-80,Santa Ana,None,NaT,"genero_invalido, fecha_nacimiento_invalida, se..."
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Hombre,06-18-79,San Miguel,None,NaT,"fecha_nacimiento_invalida, segmento_nulo"
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Hombre,1960-09-29,La Libertad,Regular,NaT,fecha_nacimiento_invalida
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,None,1945/08/02,San Salvador,Pyme,1945-08-02,genero_invalido
5,6,Ricardo López Vásquez,ricardo.lopez.vasquez6@seguro.sv,Hombre,1966/10/15,None,Pyme,1966-10-15,ciudad_nula
6,7,Diego Flores Rojas,diego.flores.rojas0@example.com,Hombre,27-07-1983,Santa Ana,Premium,NaT,fecha_nacimiento_invalida
7,8,Karla Ortiz López,karla.ortiz.lopez1@mail.com,Hombre,08-05-1975,Santa Ana,Premium,NaT,fecha_nacimiento_invalida
8,9,Juan Flores Morales,juan.flores.morales2@example.com,Mujer,14-05-1969,San Miguel,Regular,NaT,fecha_nacimiento_invalida
9,10,María Aguilar López,maria.aguilar.lopez3@example.com,Hombre,2007-03-14,San Salvador,Premium,NaT,fecha_nacimiento_invalida

In [56]:
from google.colab import files
files.download("clientes_curated_ejercicio.csv")
files.download("clientes_rejects_ejercicio.csv")